import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ClipboardList, FileCheck2, FilePlus2, Gavel } from "lucide-react";
import { useLocation } from "wouter";

const actions = [{ title: "Commissions d’affectation", description: "Créer et prévisualiser une commission selon le modèle institutionnel.", icon: ClipboardList, path: "/commission-affectation", action: "Nouvelle commission" }, { title: "PV disciplinaires", description: "Préparer un procès-verbal de transmission de dossier disciplinaire.", icon: Gavel, path: "/modeles", action: "Créer un PV" }, { title: "PV d’ouverture", description: "Ouvrir et tracer une action disciplinaire dans le circuit administratif.", icon: FilePlus2, path: "/modeles", action: "Créer un PV" }, { title: "Actes validés", description: "Consulter les documents générés, signés et archivés dans la GED.", icon: FileCheck2, path: "/documents-rapports", action: "Ouvrir la GED" }];
export default function ActesPage() { const [, setLocation] = useLocation(); const commissions = trpc.commissions.list.useQuery(); return <DashboardLayout><div className="siel-shell mx-auto min-h-[calc(100vh-2rem)] max-w-[1500px] rounded-2xl p-5 md:p-7"><div className="space-y-6"><div className="siel-section-bar rounded-xl px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-white/75">Production documentaire</p><h1 className="mt-1 text-3xl font-semibold">Actes administratifs</h1></div><p className="max-w-3xl text-muted-foreground">Créez, prévisualisez, validez et archivez les actes administratifs de la Sous-Division.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{actions.map(({ title, description, icon: Icon, path, action }) => <Card key={title} className="border-0 shadow-sm"><CardHeader><Icon className="h-8 w-8 text-primary" /><CardTitle className="mt-3 text-base">{title}</CardTitle></CardHeader><CardContent><p className="min-h-16 text-sm text-muted-foreground">{description}</p><Button onClick={() => setLocation(path)} className="mt-4">{action}</Button></CardContent></Card>)}</div><Card className="border-0 shadow-sm"><CardHeader><CardTitle>Commissions récentes</CardTitle></CardHeader><CardContent className="space-y-3">{commissions.data?.map(({ commission, school }) => <div key={commission.id} className="flex flex-col justify-between gap-2 rounded-lg border p-3 md:flex-row md:items-center"><div><p className="font-mono text-xs text-primary">{commission.reference}</p><p className="mt-1 font-medium">{commission.agentName} {commission.firstName}</p><p className="text-sm text-muted-foreground">{commission.actNature} · {school.officialName}</p></div><Badge variant="outline">{commission.status}</Badge></div>)}{!commissions.data?.length && <p className="py-4 text-sm text-muted-foreground">Aucune commission enregistrée.</p>}</CardContent></Card></div></div></DashboardLayout>; }
