import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Search } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export function DossiersPage() {
  const [query, setQuery] = useState("");
  const { data, isLoading } = trpc.dossiers.list.useQuery();
  const rows = data?.filter(({ dossier }) => `${dossier.reference} ${dossier.subject} ${dossier.sender}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm font-medium uppercase tracking-[0.18em] text-primary">Registre administratif</p><h1 className="mt-2 text-3xl font-semibold">Dossiers & courrier</h1><p className="mt-2 text-muted-foreground">Suivez les dossiers reçus, leurs bureaux responsables et leurs prochaines étapes.</p></div><Card className="border-0 shadow-sm"><CardHeader><div className="flex items-center gap-2 rounded-lg border bg-muted/30 px-3"><Search className="h-4 w-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} className="border-0 bg-transparent shadow-none focus-visible:ring-0" placeholder="Référence, objet ou expéditeur" /></div></CardHeader><CardContent className="space-y-3">{isLoading ? <p className="text-sm text-muted-foreground">Chargement…</p> : rows.map(({ dossier, office, school }) => <div key={dossier.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 md:flex-row md:items-center"><div><p className="font-mono text-xs text-primary">{dossier.reference}</p><p className="mt-1 font-medium">{dossier.subject}</p><p className="text-xs text-muted-foreground">{dossier.sender}{school ? ` · ${school.officialName}` : ""} · {office?.name ?? "Non orienté"}</p></div><div className="flex items-center gap-3"><Badge variant={dossier.priority === "urgent" ? "destructive" : "outline"}>{dossier.priority}</Badge><Badge variant="secondary">{dossier.status}</Badge></div></div>)}{!isLoading && !rows.length && <p className="py-8 text-center text-sm text-muted-foreground">Aucun dossier correspondant.</p>}</CardContent></Card></div></DashboardLayout>;
}

export function SchoolsPage() {
  const [query, setQuery] = useState("");
  const [, setLocation] = useLocation();
  const { data, isLoading } = trpc.schools.list.useQuery({ search: query || undefined });
  return <DashboardLayout><div className="siel-shell mx-auto min-h-[calc(100vh-2rem)] max-w-7xl rounded-2xl p-5 md:p-7"><div className="space-y-6"><div><p className="text-sm font-medium uppercase tracking-[0.18em] text-primary">Référentiel institutionnel</p><h1 className="mt-2 text-3xl font-semibold">Établissements scolaires</h1><p className="mt-2 text-muted-foreground">Une fiche centrale pour chaque école relevant de la Sous-Division.</p></div><Card className="border-0 shadow-sm"><CardHeader className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><CardTitle>Écoles référencées</CardTitle><div className="flex w-full items-center gap-2 rounded-lg border bg-muted/30 px-3 md:w-72"><Search className="h-4 w-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} className="border-0 bg-transparent shadow-none focus-visible:ring-0" placeholder="Nom, code ou responsable" /></div></CardHeader><CardContent>{isLoading ? <p className="text-sm text-muted-foreground">Chargement…</p> : <div className="grid gap-3 md:grid-cols-2">{data?.map(school => <button key={school.id} onClick={() => setLocation(`/ecoles/${school.id}`)} className="w-full rounded-xl border p-4 text-left transition-colors hover:bg-muted/30"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{school.officialName}</p><p className="mt-1 font-mono text-xs text-primary">{school.code}</p></div><Badge variant="outline">{school.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Niveau</p><p>{school.level}</p></div><div><p className="text-xs text-muted-foreground">Type</p><p>{school.schoolType}</p></div><div><p className="text-xs text-muted-foreground">Élèves</p><p>{school.studentCount}</p></div><div><p className="text-xs text-muted-foreground">Responsable</p><p>{school.directorName || "Non renseigné"}</p></div></div><p className="mt-4 text-xs font-semibold text-primary">Ouvrir la fiche détaillée →</p></button>)}</div>}{!isLoading && !data?.length && <p className="py-8 text-center text-sm text-muted-foreground">Aucune école trouvée.</p>}</CardContent></Card></div></div></DashboardLayout>;
}
