import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Link2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function SchoolAccountsPage() { const utils = trpc.useUtils(); const users = trpc.administration.users.useQuery(); const schools = trpc.schools.list.useQuery(); const link = trpc.administration.linkSchoolAccount.useMutation({ onSuccess: () => { toast.success("Compte école rattaché"); utils.administration.users.invalidate(); } }); const [selected, setSelected] = useState<Record<number, string>>({}); return <DashboardLayout><div className="siel-shell mx-auto min-h-[calc(100vh-2rem)] max-w-[1500px] rounded-2xl p-5 md:p-7"><div className="space-y-6"><div className="siel-section-bar flex items-center gap-4 rounded-xl px-6 py-5"><ShieldCheck className="h-8 w-8" /><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-white/75">Administration des accès</p><h1 className="mt-1 text-3xl font-semibold">Comptes des établissements</h1></div></div><p className="max-w-3xl text-muted-foreground">Après connexion, chaque responsable d’établissement est rattaché à une seule école. Il ne voit ensuite que le portail et les données de cette école.</p><Card className="border-0 shadow-sm"><CardHeader><CardTitle>Utilisateurs à rattacher</CardTitle></CardHeader><CardContent className="space-y-3">{users.data?.map(user => <div key={user.id} className="flex flex-col gap-3 rounded-xl border p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{user.name || "Utilisateur sans nom"}</p><p className="text-sm text-muted-foreground">{user.email || "Adresse non renseignée"}</p><div className="mt-2 flex gap-2"><Badge variant="outline">{user.role}</Badge>{user.schoolId && <Badge>École #{user.schoolId}</Badge>}</div></div><div className="flex w-full gap-2 md:w-[420px]"><Select value={selected[user.id] || (user.schoolId ? String(user.schoolId) : undefined)} onValueChange={value => setSelected(current => ({ ...current, [user.id]: value }))}><SelectTrigger><SelectValue placeholder="Choisir une école" /></SelectTrigger><SelectContent>{schools.data?.map(school => <SelectItem key={school.id} value={String(school.id)}>{school.officialName} · {school.code}</SelectItem>)}</SelectContent></Select><Button disabled={!selected[user.id] && !user.schoolId} onClick={() => link.mutate({ userId: user.id, schoolId: Number(selected[user.id] || user.schoolId) })} className="gap-2"><Link2 className="h-4 w-4" />Rattacher</Button></div></div>)}</CardContent></Card></div></div></DashboardLayout>; }
