import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Building2, FileText, History, Users } from "lucide-react";
import { useRoute, useLocation } from "wouter";

export default function SchoolDetailPage() { const [, params] = useRoute("/ecoles/:id"); const [, setLocation] = useLocation(); const schools = trpc.schools.list.useQuery(); const school = schools.data?.find(item => item.id === Number(params?.id)); if (schools.isLoading) return <DashboardLayout><p className="p-8 text-muted-foreground">Chargement de la fiche école…</p></DashboardLayout>; if (!school) return <DashboardLayout><div className="rounded-xl border border-dashed p-12 text-center"><p className="font-medium">École introuvable</p><Button variant="link" onClick={() => setLocation("/gestion-ecoles")}>Retour au référentiel</Button></div></DashboardLayout>; return <DashboardLayout><div className="siel-shell mx-auto min-h-[calc(100vh-2rem)] max-w-[1500px] rounded-2xl p-5 md:p-7"><div className="space-y-6"><div className="siel-section-bar flex items-center gap-4 rounded-xl px-6 py-5"><Building2 className="h-8 w-8" /><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-white/75">Fiche détaillée d’une école</p><h1 className="mt-1 text-3xl font-semibold">{school.officialName}</h1></div></div><div className="grid gap-4 md:grid-cols-4"><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Code DINACOPE</p><p className="mt-2 font-mono font-semibold text-primary">{school.code}</p></CardContent></Card><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Niveau</p><p className="mt-2 font-semibold">{school.level}</p></CardContent></Card><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Élèves</p><p className="mt-2 text-2xl font-bold">{school.studentCount}</p></CardContent></Card><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Statut</p><Badge className="mt-2">{school.status}</Badge></CardContent></Card></div><Card className="border-0 shadow-sm"><CardHeader><CardTitle>Informations générales</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Info label="Type d’établissement" value={school.schoolType} /><Info label="Responsable" value={school.directorName || "Non renseigné"} /><Info label="Territoire" value={school.territory || "Non renseigné"} /><Info label="Commune" value={school.commune || "Non renseignée"} /></CardContent></Card><div className="grid gap-4 md:grid-cols-4"><TabCard icon={Building2} title="Statistiques" value={`${school.studentCount} élèves`} /><TabCard icon={Users} title="Personnel" value={`${school.teacherCount} enseignants`} /><TabCard icon={FileText} title="Documents" value="Ouvrir la GED" onClick={() => setLocation("/documents-rapports")} /><TabCard icon={History} title="Historique" value="Voir l’audit" onClick={() => setLocation("/audit")} /></div></div></div></DashboardLayout>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function TabCard({ icon: Icon, title, value, onClick }: { icon: typeof Building2; title: string; value: string; onClick?: () => void }) { return <Card className="border-0 shadow-sm"><CardContent className="p-5"><Icon className="h-6 w-6 text-primary" /><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{value}</p>{onClick && <Button variant="link" onClick={onClick} className="mt-2 h-auto p-0">Ouvrir</Button>}</CardContent></Card>; }
