import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ClipboardList, FileCheck2, MessageSquare, Settings, ShieldCheck, UserRound } from "lucide-react";
import { useLocation } from "wouter";

const sections: Record<string, { title: string; eyebrow: string; description: string; icon: typeof UserRound; cards: string[] }> = {
  "/personnel": { title: "Personnel & affectations", eyebrow: "Gestion du personnel", description: "Suivez les agents, leurs fonctions, leurs établissements et leurs actes d’affectation.", icon: UserRound, cards: ["Liste du personnel enseignant", "Fiches agents et matricules", "Historique des affectations", "Nouvelles affectations"] },
  "/actes": { title: "Actes administratifs", eyebrow: "Production documentaire", description: "Centralisez les commissions, procès-verbaux et actes administratifs validés.", icon: ClipboardList, cards: ["Commissions d’affectation", "PV disciplinaires", "PV d’ouverture", "Actes signés"] },
  "/actes-administratifs": { title: "Actes administratifs", eyebrow: "Production documentaire", description: "Centralisez les commissions, procès-verbaux et actes administratifs validés.", icon: ClipboardList, cards: ["Commissions d’affectation", "PV disciplinaires", "PV d’ouverture", "Actes signés"] },
  "/examens": { title: "Examens", eyebrow: "Suivi scolaire", description: "Préparez les campagnes, candidats, résultats et états récapitulatifs.", icon: FileCheck2, cards: ["Campagnes en cours", "Candidats inscrits", "Résultats à publier", "États statistiques"] },
  "/communication": { title: "Communication", eyebrow: "Circulaires & alertes", description: "Diffusez les circulaires et suivez les communications adressées aux établissements.", icon: MessageSquare, cards: ["Nouvelles circulaires", "Destinataires", "Accusés de réception", "Notifications"] },
  "/parametres": { title: "Paramètres", eyebrow: "Configuration institutionnelle", description: "Configurez les séquences, bureaux, modèles et règles de la Sous-Division.", icon: Settings, cards: ["Bureaux et séquences", "Modèles documentaires", "Canaux de notification", "Préférences"] },
  "/permissions": { title: "Rôles & permissions", eyebrow: "Gouvernance", description: "Administrez les rôles et les permissions d’action avec une traçabilité complète.", icon: ShieldCheck, cards: ["Rôles applicatifs", "Permissions par action", "Affectations bureaux", "Journal d’audit"] },
  "/utilisateurs": { title: "Utilisateurs", eyebrow: "Gestion des accès", description: "Gérez les comptes, rôles, bureaux de rattachement et statuts d’activation.", icon: UserRound, cards: ["Utilisateurs actifs", "Invitations", "Rôles", "Historique des accès"] },
  "/bureaux": { title: "Bureaux", eyebrow: "Organisation", description: "Structurez les bureaux et les circuits de traitement de la Sous-Division.", icon: Settings, cards: ["Bureaux actifs", "Responsables", "Séquences", "Affectations"] },
};

export default function SectionPage() { const [location, setLocation] = useLocation(); const section = sections[location] ?? sections["/personnel"]; const Icon = section.icon; const targets = location === "/personnel" ? ["/utilisateurs", "/personnel", "/commission-affectation", "/commission-affectation"] : location === "/actes-administratifs" || location === "/actes" ? ["/commission-affectation", "/rapports", "/commission-affectation", "/ged"] : location === "/portail-ecoles" ? ["/rapports", "/rapports", "/ged", "/statistiques"] : section.cards.map(() => location); return <DashboardLayout><div className="siel-shell min-h-[calc(100vh-2rem)] rounded-2xl p-6"><div className="mx-auto max-w-7xl space-y-8"><div className="siel-section-bar flex items-center gap-4 rounded-xl px-6 py-5"><Icon className="h-8 w-8" /><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-white/75">{section.eyebrow}</p><h1 className="mt-1 text-3xl font-semibold">{section.title}</h1></div></div><p className="max-w-3xl text-muted-foreground">{section.description}</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{section.cards.map((card, index) => <Card key={card} className="border-0 shadow-sm transition-transform hover:-translate-y-0.5"><CardHeader><div className={`mb-2 h-2 w-12 rounded-full ${index % 4 === 0 ? "bg-blue-600" : index % 4 === 1 ? "bg-emerald-500" : index % 4 === 2 ? "bg-orange-500" : "bg-violet-600"}`} /><CardTitle className="text-base">{card}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Vue structurée et traçable</p><Button variant="link" onClick={() => setLocation(targets[index] ?? location)} className="mt-3 h-auto p-0">Ouvrir la vue</Button></CardContent></Card>)}</div></div></div></DashboardLayout>; }
